version: '3.8'

services:
  db:
    container_name: nest-course
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest-course
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432